[project]
name = "infer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.0.0",
    "tabulate>=0.9.0",
    "torch>=2.9.1",
    "transformer-lens>=2.16.1",
]
